#include "stdint.h"
#include "usb_hid_keys.h"

uint8_t  KITE_KEYMAP[ 66 ] = {
	KEY_B, KEY_X,
	KEY_C, KEY_J,
	KEY_D, KEY_E,
	KEY_E, KEY_DOT,
	KEY_F, KEY_U,
	KEY_G, KEY_I,
	KEY_H, KEY_D,
	KEY_I, KEY_C,
	KEY_J, KEY_H,
	KEY_K, KEY_T,
	KEY_L, KEY_N,
	KEY_N, KEY_B,
	KEY_O, KEY_R,
	KEY_P, KEY_L,
	KEY_Q, KEY_APOSTROPHE,
	KEY_R, KEY_P,
	KEY_S, KEY_O,
	KEY_T, KEY_Y,
	KEY_U, KEY_G,
	KEY_V, KEY_K,
	KEY_W, KEY_COMMA,
	KEY_X, KEY_Q,
	KEY_Y, KEY_F,
	KEY_Z, KEY_SEMICOLON,
	KEY_APOSTROPHE, KEY_MINUS,
	KEY_COMMA, KEY_W,
	KEY_DOT, KEY_V,
	KEY_EQUAL, KEY_RIGHTBRACE,
	KEY_LEFTBRACE, KEY_SLASH,
	KEY_MINUS, KEY_LEFTBRACE,
	KEY_RIGHTBRACE, KEY_EQUAL,
	KEY_SEMICOLON, KEY_S,
	KEY_SLASH, KEY_Z
};

/*
 * Dvorak layout
 */
